# -*- coding: utf-8 -*-
"""Langchain_PDF_Groq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVJy21ZV_buHwmRC3B7obLTeOw-WsnAO
"""

!pip install -q cassio datasets langchain openai tiktoken

pip install -U langchain langchain-community cassio

pip install langchain langchain-community langchain-core langchain-groq cassio

pip install -U langchain langchain-community cassio

pip install -U langchain langchain-community langchain-core langchain-groq cassio

!pip install -U langchain langchain-community cassio

!pip install -U langchain langchain-community langchain-openai cassio

!pip uninstall -y langchain
!pip install -U langchain langchain-community langchain-openai cassio

!pip install -U langchain-text-splitters

!pip uninstall -y langchain
!pip install -U \
  langchain \
  langchain-community \
  langchain-openai \
  langchain-text-splitters \
  cassio

!pip install PyPDF2

from langchain_community.vectorstores import Cassandra
# Cassandra vector store integration for storing and retrieving embeddings in AstraDB/Cassandra

from langchain_text_splitters import CharacterTextSplitter
# Splits large text into smaller chunks based on character length

from langchain_openai import ChatOpenAI
# OpenAI chat model wrapper (GPT models) used as LLM

from langchain_core.prompts import ChatPromptTemplate
# Creates structured chat prompts for LLM input formatting

from langchain_core.output_parsers import StrOutputParser
# Converts LLM output into plain string format

from langchain_core.runnables import RunnablePassthrough
# Passes input directly through a LangChain pipeline step (used in chains)

from langchain_community.embeddings import HuggingFaceBgeEmbeddings
# Generates text embeddings using BGE models from HuggingFace

from PyPDF2 import PdfReader
# Reads and extracts text from PDF files

import cassio
# Connects LangChain with DataStax AstraDB (Cassandra cloud database)

from PyPDF2 import PdfReader

#A security token used to authenticate your app with Astra DB (Cassandra cloud database).
ASTRA_DB_APPLICATION_TOKEN ="AstraCS:IdUWOTHuNgvRebAOqLhAIivt:cefc428c36f90a88d6e48360d6f5f19fdcd3f9e7937b19ebfeb4c08ea8fd49f8"
# Unique Database ID of your Astra DB instance
ASTRA_DB_ID="7d70d46c-b7b8-4789-83f1-d8e64f1b1996"
# API key to access Groq LLM models.

GROQ_API_KEY="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"

# provide the path of  pdf file/files.
pdfreader = PdfReader('budget_speech.pdf')

from typing_extensions import Concatenate
# read text from pdf
raw_text = ''
for i, page in enumerate(pdfreader.pages):
    content = page.extract_text()
    if content:
        raw_text += content

raw_text

cassio.init(token=ASTRA_DB_APPLICATION_TOKEN, database_id=ASTRA_DB_ID)

from langchain_groq import ChatGroq
from langchain_community.embeddings import HuggingFaceEmbeddings
import os

# Set Groq API Key
os.environ["GROQ_API_KEY"] = "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"

# Groq LLM
llm = ChatGroq(
    model="llama3-8b-8192"   # or "mixtral-8x7b-32768"
)

# Embeddings (Groq does NOT provide embeddings)
embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Imports the Cassio library

#Cassio connects LangChain with Astra DB (Cassandra cloud database)
import cassio

cassio.init(
    token="AstraCS:IdUWOTHuNgvRebAOqLhAIivt:cefc428c36f90a88d6e48360d6f5f19fdcd3f9e7937b19ebfeb4c08ea8fd49f8",
    database_id="7d70d46c-b7b8-4789-83f1-d8e64f1b1996"
)

#  mports HuggingFace embedding wrapper from LangChain.

#This allows you to convert text → numerical vectors
from langchain_community.embeddings import HuggingFaceEmbeddings

embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

astra_vector_store = Cassandra(
    embedding=embedding,
    table_name="qa_mini_demo_v2",
)

from langchain_text_splitters import CharacterTextSplitter

!pip install -U langchain-text-splitters

from langchain_text_splitters import CharacterTextSplitter

text_splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=800,
    chunk_overlap=200
)
texts = text_splitter.split_text(raw_text)

texts[:50]

# loading the data from the vector of the store

retriever = astra_vector_store.as_retriever()

astra_vector_store.add_texts(texts)
print("Inserted %i documents." % len(texts))

retriever = astra_vector_store.as_retriever()

astra_vector_store.add_texts(texts)
print("Inserted %i documents." % len(texts))

first_question = True
while True:
    if first_question:
        query_text = input("\nEnter your question (or type 'quit' to exit): ").strip()
    else:
        query_text = input("\nWhat's your next question (or type 'quit' to exit): ").strip()

    if query_text.lower() == "quit":
        break

    if query_text == "":
        continue

    first_question = False

    print("\nQUESTION: \"%s\"" % query_text)
    answer = astra_vector_index.query(query_text, llm=llm).strip()
    print("ANSWER: \"%s\"\n" % answer)

    print("FIRST DOCUMENTS BY RELEVANCE:")
    for doc, score in astra_vector_store.similarity_search_with_score(query_text, k=4):
        print("    [%0.4f] \"%s ...\"" % (score, doc.page_content[:84]))